FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src/
COPY configs/ ./configs/
COPY scripts/train_distributed.py ./scripts/

ENV PYTHONPATH=/app
EXPOSE 50051

CMD ["python", "scripts/train_distributed.py", "--dataset", "cic-iomt", "--task", "binary", "--partitions", "6"]
